### ISSUE TITLE
Weed Suppression

### ISSUE THREAD

**Issue by Jayshua83** [Timmeey86/FS22_ConservationAgriculture#16]
Weed Suppression was used and now I have dots of weeds ALL over my fields! Is this intended?

**Comment by Jayshua83** [comment]
![Screenshot_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/11082446/13e61b03-f6fb-434c-a82e-a8afdcd98d17)

**Comment by Timmeey86** [comment]
This is not intended, I'll have to look into this. Can you let me know which map you were using and if this was with or without precision farming?

**Comment by Jayshua83** [comment]
Without PF.

Highly Edited version of Frankenmuth MI map. Although I don't think I changed any ground types or weed related things.

**Comment by Jayshua83** [comment]
I can send the zip too you if needed!

**Comment by Timmeey86** [comment]
I'd try and reproduce it on the unmodified map first. Could you tell me the last 4-5 things you did to the field? (e.g. harvested corn -> left barren for a bit -> planted oilseed radish -> rolled it down, or similar)

**Comment by Jayshua83** [comment]
Harvested Canola > Lime > Fertilizer > Oilseed Radish Seeded > Replanted Canola > Fertilizer Again

Settings were as follows.

![Screenshot_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/11082446/f44ab55d-7485-46c6-9696-7cb7e2359085)

**Comment by Jayshua83** [comment]
We got the Mulched Status from Planting Canola but Obviously with our settings and not reading it we had to fertilize a 2nd time since we already did a 1st stage ourselves and should have NOT done any Fert first... But we have a new Field Prep order now. lol :)

**Comment by Timmeey86** [comment]
Since you say "we", I guess this is multiplayer? If so, do you happen to have a backup save from before you seeded canola and could try if you get the same result if you seed canola in singleplayer?
I'll try reproducing it on my end in the meantime

**Comment by Jayshua83** [comment]
Yeah it is a Dedi Server with my wife and I. Not sure about saves. There have been a lot since... Might have overwritten by now... But I can try in SP later on...

**Comment by Jayshua83** [comment]
These were the first fields we have did since starting CA... We will have more later and I will be interested to see if they have similar results or if this is a one off or something...

**Comment by Timmeey86** [comment]
Some initial testing results: 
The way I implemented weed suppression does not remove any weeds, it just prevents new ones.

So if you do 

- Harvest canola
- Plant oilseed radish (OSR)
- Use weeder on OSR
- Sleep
- Seed Canola into OSR

you won't have any weeds

If you skip the weeding step, you'll have weeds in your OSR. If you direct seed into that, the weeds will not be visible, but still there, and the next month you'll see them again.

However, I guess it would make sense to have weed suppression terminate existing weeds, too, since they'd be crimped and also covered with the biomass from the OSR so they wouldn't get enough sunlight to recover maybe

**Comment by Jayshua83** [comment]
I thought OSR just didn't allow weeds cause I didn't see any. lol. Hrmph.. Well I might be able to turn that off in map xmls too if that is what is happening...

Although I think it is already set on most maps? 

plantsWeed="false" is on OSR just like Grass/Meadow...

None of my other OSR fields have weeds...

**Comment by Jayshua83** [comment]
Also OSR <cropCare maxWeederState="0" maxWeederHoeState="0" /> like Grass/Meadow...

**Comment by Timmeey86** [comment]
Ok yeah this is kind of weird. I did:

Elmcreek map, only my mod + easy def + real speed limit (to speed the test up)

1. Buy a canola field
2. Harvest a strip
3. Direct seed OSR into the strip and into the field a bit
4. Sleep
5. No weeds are shown in the map
6. Direct seed Canola into OSR, and on the harvested strip, and into the field

Result: No visual weeds where there was OSR and where there was the field
But the map shows weeds almost everywhere:

![grafik](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/10223149/1f44dfa0-62ce-4c94-b5cf-76263fe66d51)
![grafik](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/10223149/273ee9ec-282e-46e4-bda4-f061991d5cbd)

**Comment by Timmeey86** [comment]
Did a similar test with base game: The map behaves the same, but the weeds are visible in the field.
So it looks like my mod only removes the visual effects rather than the actual ones

**Comment by Timmeey86** [comment]
@Jayshua83 This should no longer happen. Please reopen if it does

**Comment by Timmeey86** [comment]
New release published: https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.0.6
