### ISSUE TITLE
Not an Issue, just a question.

### ISSUE THREAD

**Issue by LumberingTroll** [Timmeey86/FS22_ConservationAgriculture#18]
Sorry, I know this isn't the best place for this but wasn't sure where else to ask you. What reshade preset are you using in your screen shots? they look fantastic.

**Comment by Timmeey86** [comment]
Check this post on reddit for the settings: https://www.reddit.com/r/farmingsimulator/comments/16wbjib/comment/k2w3e5d/?utm_source=share&utm_medium=web2x&context=3
