### ISSUE TITLE
Feature Requets: Fertilize the field when chopping straw

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS22_ConservationAgriculture#22]
Currently, chopping straw is less economically feasible than swathing and baling it. This could be balanced by making chopped straw fertilize the field.
Requested by @chrisasst on YouTube

**Comment by Timmeey86** [comment]
@DrewCZ This is now implemented for base game in branch https://github.com/Timmeey86/FS22_ConservationAgriculture/tree/feature/fixed-fertilization

I haven't managed to get it working with Precision Farming yet - it will always fully fertilize the field, no matter what I try.
I've got one final idea how it might work, but that would require me configuring straw as a regular fertilizer type and adding precision farming details for that. That'll be a lot of implementation and tests, though

**Comment by Timmeey86** [comment]
Got it working for precision farming, too. It will also be possible to adjust the amount

**Comment by DrewCZ** [comment]
wow! A lot of implementation was 18 hours of hard work :-D
thank you so much!

**Comment by Timmeey86** [comment]
Well, I'm still in the testing phase, but I luckily identified a new approach which turned out to be much simpler.
I'm still in the testing phase, so the code on github doesn't contain that feature yet

**Comment by Timmeey86** [comment]
@DrewCZ This should work now in the branch I linked above. Some things are not working as intended, yet, though, like cultivators, for example

Direct seeders will also always leave a straw texture even when seeding into freshly plowed ground. This is a drawback I currently have to accept in order to make the fixed fertilization amount work for direct seeders
