### ISSUE TITLE
Slurry Cultivators reach max fertilisation instantly when Cultivator Incorporation is turned on (and using cultivators on ploughed ground gives the wrong texture)

### ISSUE THREAD

**Issue by awesomef2004** [Timmeey86/FS22_ConservationAgriculture#31]
Had a field with Oilseed Radish, and used a slurry cultivator. This led to instant max fertilisation (200kg/ha), even when fertilising rate was set to the minimum (end result should have been 45kg/ha - 40kg/ha from oilseed radish and 5 from slurry). When slurry was turned off, fertilisation was as expected (40kg/ha). When I turned off cultivator incorporation, expected behaviour occurred with slurry turned on and off (45kg/ha when slurry was on, and 40kg/ha when slurry was turned off)

Also additionally (not sure if relevant or a separate issue) when cultivating with cultivator incorporation turned on, you always get the texture with straw spread on it (check screenshots linked). When cultivator incorporation is turned off, you get expected cultivator textures

I have screenshots, screen recording and the log linked.

[https://drive.google.com/drive/folders/1N-UBgUETlwG0ICZ1AOwzqGd0ABMMFJQq?usp=sharing](url)

**Comment by Timmeey86** [comment]
Hi, thanks for your feedback, I will look into this issue.

About the straw texture, from the mod description:
> Note: When using a direct seeder or a cultivator with this mod, the ground will always look like chopped straw.
The current implementation of the configurable nitrogen bonus unfortunately requires it to be this way for the time being.

Without the straw texture, I would get the 200kg/ha effect with cultivators all the time, it has to do with how precision farming "locks" ground in order to remember that it has already been processed. This is most likely also what fails with slurry cultivators.

**Comment by Timmeey86** [comment]
This is a tough one, I couldn't find an easy fix, so it will take some time

**Comment by awesomef2004** [comment]
I imagined it would be a complex issue, I'm not a programmer, but I couldn't work out where it was going wrong. If you need any other info or if I can help in any capacity, let me know.

**Comment by Timmeey86** [comment]
The main issue is that the Precision Farming source code is not openly available, unlike most of the other stuff I need for this mod.

In this specific case, Precision Farming does something between my code and the base game code (which is on Giants Developer Network) so I need to try and fool PF into thinking it has already processed the area. It worked by "fertilizing" the ground with straw for many cases, but in this case it looks like PF does things differently

**Comment by awesomef2004** [comment]
I tried that branch, works as you said. Thank you for the work on this mod. Hopefully Giants releases the Precision Farming source code, no reason not to

**Comment by awesomef2004** [comment]
I have bad news. That branch and the most recent main branch have the same issue. If you try to buy a seeder or a planter, the seeder's 3d model does not load. Seed hoppers will work as normal. I tired it with Conservation Agriculture as the only mod installed, and had the same error. If you buy a seeder with the mod inactive, then load the save after activating the mod, the game will get stuck at 85% loading. I have attached the logs
![Conservation agriculture log no mods](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/161907431/e39f7dde-7335-41bb-a983-316d4448a4a5)
[conservation agriculturelog.txt](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14580507/conservation.agriculturelog.txt)

**Comment by Timmeey86** [comment]
I'm currently not at home and can't find an obvious issue. Can you send me the log file when using the version from the main branch, please, since it logs more information?

**Comment by awesomef2004** [comment]
Yes I have a link here with a full log and screen recording demonstrating the issue as well

https://drive.google.com/drive/folders/1LfawilWcb_Gfl7wmDoA8NEY3aPMtjJVk?usp=sharing

**Comment by awesomef2004** [comment]
I have a link here with the full log and a screen recording.

https://drive.google.com/drive/folders/1LfawilWcb_Gfl7wmDoA8NEY3aPMtjJVk?usp=sharing

**Comment by Timmeey86** [comment]
I believe the issue occurs since you changed the name of the zip file. Does it work if you call it exactly "FS22_ConservationAgriculture.zip"?

**Comment by awesomef2004** [comment]
That was exactly it. Never had that happen before. Sorry for wasting your time

**Comment by Timmeey86** [comment]
Lol you're not wasting any time. It's low effort programming on my side, but with renaming you can fix it right now; I can't fix the code yet

**Comment by Timmeey86** [comment]
The main branch now supports having zip files with different names ;-)
