### ISSUE TITLE
oilseed radish turns into parsnip

### ISSUE THREAD

**Issue by Joelminer-satisfactory** [Timmeey86/FS22_ConservationAgriculture#32]
When I plant oilseed radish with this mod enabled, parsnip grows instead.

**Comment by Timmeey86** [comment]
Hi, which version of the mod are you using?

**Comment by Joelminer-satisfactory** [comment]
its v1.0.0.8, but i think it may have been a faulty install, as now the issue seems to no longer occur
[log.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474105/log.zip)

**Comment by Joelminer-satisfactory** [comment]
I am using v1.0.0.8 but i think something was wrong with my install of the mod, the issue doesn't seem to occur anymore after re-installing

**Comment by Timmeey86** [comment]
Alright, let me know if the issue occurs again, and as I said, please provide the log file so I can see which mods you are using and if errors related to fruit types were logged

**Comment by Joelminer-satisfactory** [comment]
[log.txt.2024-02-11_17-13-23.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474170/log.txt.2024-02-11_17-13-23.zip)
[log.txt.2024-02-11_17-19-12.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474171/log.txt.2024-02-11_17-19-12.zip)
[log.txt.2024-02-12_19-32-52.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474172/log.txt.2024-02-12_19-32-52.zip)
[log.txt.2024-02-13_06-52-41.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474173/log.txt.2024-02-13_06-52-41.zip)
[log.txt.2024-02-13_06-56-26.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474174/log.txt.2024-02-13_06-56-26.zip)
[log.txt.2024-03-03_08-47-36.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474175/log.txt.2024-03-03_08-47-36.zip)
[log.txt.2024-03-03_09-09-26.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474176/log.txt.2024-03-03_09-09-26.zip)
[log.txt.2024-03-03_09-35-44.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474177/log.txt.2024-03-03_09-35-44.zip)
[log.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474178/log.zip)
[log.txt.2024-02-11_16-56-15.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474179/log.txt.2024-02-11_16-56-15.zip)
[log.txt.2024-02-11_17-07-29.zip](https://github.com/Timmeey86/FS22_ConservationAgriculture/files/14474180/log.txt.2024-02-11_17-07-29.zip)
here are all the log files that are in the folder, idk in which ones the issue occurs

**Comment by Timmeey86** [comment]
Judging by the log files, you were using version 1.0.0.6 which had this issue. It should no longer happen with v1.0.0.8
