### ISSUE TITLE
Issue with this mod and Alma's map...

### ISSUE THREAD

**Issue by FirenzeIT** [Timmeey86/FS22_ConservationAgriculture#37]
Hi @Timmeey86, unfortunately with the latest modhub update of this mod, there are densitymap errors and warnings... in the Alma map (currently I only tested this of the custom map), I attach screenshot and log below, as a view and check. All this, happens when I use any cultivator and plough (log_2 + log_3).
[log_2.txt](https://github.com/user-attachments/files/15752583/log_2.txt)
[log_3.txt](https://github.com/user-attachments/files/15752584/log_3.txt)

Without the conservation mod, no errors are reported in the log (the first one, attach below).
[log.txt](https://github.com/user-attachments/files/15752595/log.txt)

![1248130_20240609014436_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/2ca78760-d8a5-4557-b77e-04a822f59900)

**Comment by Timmeey86** [comment]
I cannot reproduce this with Alma + Conservation Agriculture only, so a third mod must be involved. This will take a while

**Comment by FirenzeIT** [comment]
> I cannot reproduce this with Alma + Conservation Agriculture only, so a third mod must be involved. This will take a while

Hi, i just tried now with only few mods (all from modhub) and i have yet this type of issues... Without Conservation mod, i don't have any of this triggered issues/problems..

[log.txt](https://github.com/user-attachments/files/16075098/log.txt)

![1248130_20240703011105_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/8d814eba-679d-45f6-9174-c3078eb223fe)
![1248130_20240703011200_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/fb0d07ac-9fdf-4b06-9741-2b26232a6799)
![1248130_20240703011231_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/d97d3c1c-5477-487d-b557-36850d732288)
![1248130_20240703011237_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/4c033714-a8c3-44fa-80e0-a33ae5e7caeb)

**Comment by Timmeey86** [comment]
It seems to be a conflict with the Lubricating Grease mod but I could not find the cause this morning. Will continue debugging later today

**Comment by FirenzeIT** [comment]
Hi, ok i also continue this testing with and without grease addon, and
updated you when i find the culprit 👍🏻

Il Mer 3 Lug 2024, 11:03 Timmeey86 ***@***.***> ha scritto:

**Comment by FirenzeIT** [comment]
Hi, ok i also continue this testing with and without grease addon, and
updated you when i find the culprit 👍🏻

EDIT: I tried also without Lubricating Grease addon and RealDashboard, this errors it's continuosly.. So the culprit it's Conservation ofc..

[log.txt](https://github.com/user-attachments/files/16084940/log.txt)

![1248130_20240703142228_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/d9c8dc6c-742c-43b3-b02b-99cade92b4ae)
![1248130_20240703143034_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/7b648aa0-4d4d-4335-90a6-d0fb76eb936a)

**Comment by Timmeey86** [comment]
I've got a savegame where I can 100% reproduce it now with just Alma, CA and Easy Dev active. It only seems to happen when the cultivator touches both the field and the field border, which is why I couldn't reproduce it in some tests.

Now I need to find the code part which causes this. The errors are unfortunately not helpful since there is only a path to Giants Code, not to my mod.

**Comment by Timmeey86** [comment]
The error happens while trying to use the "Weed Suppression" feature.

However, it seems to be an issue with Alma Missouri itself: If I buy a weeder on Alma without any mods and try to use it, I get the same errors:
![image](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/10223149/bd38a72d-0ea3-4b4f-9dfb-bf511d18bb4c)

**Comment by FirenzeIT** [comment]
Ok but i use and tried only cultivator and have the errors with this type
of implements.. I could try without this option enable too..

Il Mer 3 Lug 2024, 20:31 Timmeey86 ***@***.***> ha scritto:

**Comment by Timmeey86** [comment]
This release should fix the errors: https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.1.5

Not sure about the low speed

**Comment by FirenzeIT** [comment]
Now loop of errors when i clicked for hire man of work... o.O

![1248130_20240703215213_1](https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/113168067/648ad0c2-b0f1-4aa3-922e-27ec7216aac5)

[log.txt](https://github.com/user-attachments/files/16090191/log.txt)

**Comment by Timmeey86** [comment]
Alright. In that case please revert to version 1.0.1.4 and turn weed suppression off. I'm afraid there is nothing else I can try right now. I contacted the map maker of Alma, let's see if they respond

**Comment by Timmeey86** [comment]
@FirenzeIT Please test [Release v1.0.1.6](https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.1.6)

**Comment by FirenzeIT** [comment]
> @FirenzeIT Please test [Release v1.0.1.6](https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.1.6)

Hi. ok when i have a little time, i test this update, thank you.

**Comment by Timmeey86** [comment]
That's weird, I can no longer reproduce it. Can you upload a ZIP file of your save game and tell me the exact steps you do to get the error, please?

**Comment by FirenzeIT** [comment]
> That's weird, I can no longer reproduce it. Can you upload a ZIP file of your save game and tell me the exact steps you do to get the error, please?

Hi, this is the steps which i follow:
I lower the cultivator (as in screenshot) and immediately the error is triggered, or if not immediately, after a few seconds when I go forward. Whereas with weed suppression turned off, no error is triggered. 
Version 1.0.1.6.

2024-07-05 22:20 Error: Invalid object parameter in DensityMapFilter.
2024-07-05 22:20 DensityMapFilter: called from dataS/scripts/utils/FSDensityMapUtil.lua (1955)
2024-07-05 22:20 Error: Invalid object parameter in DensityMapFilter.
2024-07-05 22:20 DensityMapFilter: called from dataS/scripts/utils/FSDensityMapUtil.lua (1955)
2024-07-05 22:20 Error: Invalid object parameter in DensityMapFilter.

[log.txt](https://github.com/user-attachments/files/16113589/log.txt)

**Comment by Timmeey86** [comment]
I can't reproduce it based on logs and screenshots unfortunately:

https://github.com/Timmeey86/FS22_ConservationAgriculture/assets/10223149/c3158dbe-1fad-4fda-a210-2fd25cb4c80d

So I need you to go to your Documents/My Games/FarmingSimulator2022 folder and create a .zip file of the save game folder of this Alma save and upload it here

**Comment by FirenzeIT** [comment]
I just done this.

Il Sab 6 Lug 2024, 09:47 Timmeey86 ***@***.***> ha scritto:

**Comment by Timmeey86** [comment]
My bad, didn't see your edited message.

Version 1.0.1.7 should now fix it for good:
https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.1.7

**Comment by Timmeey86** [comment]
@FirenzeIT Did you get the chance to test it yet?

**Comment by FirenzeIT** [comment]
> @FirenzeIT Did you get the chance to test it yet?

Not yet sorry, tomorrow evening (Italy's local time) sure, ofc!
